### ISSUE TITLE
error: Cannot read properties of undefined (reading 'retweeted_status_result')

### ISSUE THREAD

**Issue by YiniRuohong** [prinsss/twitter-web-exporter#31] opened 2024-06-15 15:47 UTC
When I tried to export bookmarks, I encountered the following error: 
error: Cannot read properties of undefined (reading 'retweeted_status_result'). 
I am using the Arc browser on macOS, version: latest version.
I'm not sure if this is related to me adding too many bookmarks (548).
<img width="309" alt="screenshot2024-06-15 23 40 46" src="https://github.com/prinsss/twitter-web-exporter/assets/61607977/06415e72-cf70-4e86-af42-d54fdbe5ec4c">
I've checked all issues but cannot get the solution of this problem.
thanks a lot! wish you have a good day：)

**Comment by prinsss** [comment] 2024-06-16 07:51
Hi,

Thanks you for your feedback. Please open your browser's DevTools (by pressing ⌘⌥I) and check the console for more detailed error messages.

Would you mind sharing the API response which caused the error? You can do this by following these steps:

(The response data may contain sensitive information, so please review it before sharing it here. Or you can send it to my personal email: hi at prin dot studio)

![CleanShot 2024-06-16 at 15 36 03 2](https://github.com/prinsss/twitter-web-exporter/assets/11206497/f050cff1-11c5-4a20-a2f9-25f64dac8f19)

**Comment by YiniRuohong** [comment] 2024-06-16 10:08
hi! thanks for your timely help!
I've sent a mail includes the response contents you need, my mail is i at atago dot moe
and this a picture that my console prints
<img width="549" alt="截屏2024-06-16 18 06 37" src="https://github.com/prinsss/twitter-web-exporter/assets/61607977/fcb1dec4-8f85-4346-8821-9987abb6117b">

**Comment by prinsss** [comment] 2024-06-16 10:17
@YiniRuohong Thank you. I have received your email.

However, the response seems to be not very helpful, since it does not contain any tweet. This could happen if you reached the end of your bookmark list.

Could you please reload the webpage and try it again? **Once the error occurs**, please send me the latest API response at that moment. The correct response should be much longer than the provided one.

**Comment by YiniRuohong** [comment] 2024-06-16 10:29
I apologize for my mistake, I have found the contents you need and resent a mail to you

**Comment by prinsss** [comment] 2024-06-16 10:44
I have identified the cause of the error with the help of data you provided. It seems that Twitter does not return some fields when there is an error about a tweet.

This issue should be fixed in the next release. Thank you for your feedback!

**Comment by YiniRuohong** [comment] 2024-06-16 10:45
Thanks for your timely help! have a good day!

**Closed** 2024-06-16 10:50 UTC
Labels: bug

**Comment by prinsss** [comment] 2024-06-17 03:12
The latest nightly build should have fixed this issue. Please give it a try and let me know if it works for you.

https://github.com/prinsss/twitter-web-exporter/releases/download/nightly/twitter-web-exporter.user.js

**Comment by YiniRuohong** [comment] 2024-06-17 03:26
Everything is working fine now! I can now export bookmark content and media files normally. Thank you for your support!
