### ISSUE TITLE
Export Button Missing

### ISSUE THREAD

**Issue by weeks888** [prinsss/twitter-web-exporter#4] opened 2024-02-17 18:01 UTC
<img width="1201" alt="Screenshot 2024-02-17 at 12 00 15 PM" src="https://github.com/prinsss/twitter-web-exporter/assets/125565722/65fcc364-2e7d-40be-8c07-ada69a192e8e">

Having issues with getting export button to populate

**Comment by prinsss** [comment] 2024-02-17 18:05
Duplicate of https://github.com/prinsss/twitter-web-exporter/issues/2

Scroll down in the dialog and the buttons then should show up.

**Comment by weeks888** [comment] 2024-02-17 18:21
Excellent. Rows per page was not showing up, played with screen size vertically and it now populates (not positive this was related), then Hovered over rows per page and scrolled down and export button was there - thank you.

**Closed** 2024-02-17 18:22 UTC
